### ISSUE TITLE
Any chance including a youtube on Blazor deployment on IIS 10

### ISSUE THREAD

**Issue by jcasement** [claudiobernasconi/FinanceMentor#1]
@claudiobernasconi
I've taken your Blazor crash course and it's working great on my development Win 10 machine but when trying to browse locally (http:\\localhost:60222), after deployment,  I'm getting http error 401.2 unauthorized.

I've followed this base article on how to configure IIS 10 (mine is on Win server 2019).
But I'm using the latest runtime, hosting bundle etc.
https://social.technet.microsoft.com/wiki/contents/articles/51588.blazor-deploying-an-application-on-iis-10.aspx

Any ideas are greatly appreciated on what I've done wrong since it looks like there is no authentication in this app.

**Comment by claudiobernasconi** [comment]
I can confirm that I do not use any authentication in this sample app. However, I'm not an IIS user and therefore I cannot help you with your issue. What is your goal? Why would you want to run this application on an IIS?

I do not plan to record a video about IIS in the near future. I hope you'll find a solution to your problem.

**Comment by jcasement** [comment]
@claudiobernasconi
Thank you for the confirmation on the no auth usage.
The reason for IIS is simple.  We are an IIS shop and that's what our current ASP.Net webforms runs on.
So I have to be able to deploy a new Blazor app to that IIS web server.

Thanks again for the great course work and hopefully I'll resolve my IIS issues.
